jandraApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('catalog/', include('mainApp.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/catalog/', permanent=False)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('create/', views.create_ropa, name='create'),
    path('ropa/<pk>/', views.RopaDetailView.as_view(), name='ropa-detail'),
    path('edit/<pk>/', views.RopaEditView.as_view(), name='ropa-edit'),
    path('ropa/<pk>/create', views.create_ropainstance, name='ropainstance-create'),
    path('ropa/<pk>/delete', views.RopaDeleteView.as_view(), name='ropa-delete'),
    path('ropa/instance/<pk>', views.RopaInstanceDetailView.as_view(), name='ropainstance-detail'),
    path('ropa/instance/<pk>/delete', views.RopaInstanceDeleteView.as_view(), name='ropainstance-delete'),
    path('ropa/instance/<pk>/transfer', views.transfer_stock, name='transfer-stock'),
    path('ropa/instance/<pk>/return', views.return_ropa, name='mark-returned'),
    path('search/', views.search, name='search')
]

mainApp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid


class Ropa(models.Model):
    cod = models.CharField("codigo de producto", primary_key=True, max_length=7)
    name = models.CharField(max_length=200)
    precio = models.FloatField(help_text='Precio de tu producto', null=True)
    categoria = models.ForeignKey('Categoria', help_text='Elige la Categoria de tu producto', on_delete=models.SET_NULL, null=True)
    desc = models.CharField(max_length=200)
    stock = models.IntegerField(verbose_name="Stock del producto", help_text='El stock existente del producto', null=True)
    image = models.ImageField(upload_to='ropa_image', blank=True)

    def __str__(self):
        return "COD: %s NAME: %s" % (self.cod, self.name)

    def get_absolute_url(self):
        return reverse('ropa-detail', args=[self.cod])

    def get_edit_url(self):
        return reverse('ropa-edit', args=[self.cod])


class RopaInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID unica para cada copia de la ropa")
    ropa = models.ForeignKey(Ropa, on_delete=models.SET_NULL, null=True)
    posesion = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    talle = models.ForeignKey('Talle', on_delete=models.SET_NULL, null=True, help_text="Selecciona un talle para tu ropa")
    color = models.ForeignKey('Color', on_delete=models.SET_NULL, null=True, help_text="Selecciona un color para tu ropa")

    ROPA_ESTADO = (
        ('a', 'En posesion del admin'),
        ('e', 'Entregada'),
        ('v', 'Vendida'),
        ('d', 'Devuelta'),
    )
    estado = models.CharField(max_length=1, choices=ROPA_ESTADO, blank=True, default='a', help_text='Estado de la ropa')

    class Meta:
        ordering = ["ropa"]
        permissions = (
                        ("can_mark_returned", "Poner ropa como devuelta"),
                        ("can_create_ropa", "Puede crear ropa"),
                      )

    def __str__(self):
        return "Instancia de %s, en posesion de %s, talle %s, color %s" % (self.ropa, self.posesion, self.talle, self.color)

    def get_absolute_url(self):
        return reverse('ropainstance-detail', args=[self.id])

    def get_copies_count(self):
        copies = RopaInstance.objects.filter(estado=self.estado, talle=self.talle, color=self.color, posesion=self.posesion).count()
        return copies


class Color(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Talle(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Categoria(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

mainApp/forms.py
from django import forms
from .models import Ropa, Color, Talle
from django.contrib.auth.models import User, Group


class RopaModelForm(forms.ModelForm):
    class Meta:
        model = Ropa
        fields = ['cod', 'name', 'categoria', 'precio', 'desc', 'image']


class RopaEditForm(forms.ModelForm):
    class Meta:
        model = Ropa
        fields = ['name', 'precio', 'categoria', 'desc', 'image']


class RopaInstanceCreateForm(forms.Form):
    color = forms.ModelChoiceField(queryset=Color.objects.all(), help_text='Elige un color para tu stock')
    talle = forms.ModelChoiceField(queryset=Talle.objects.all(), help_text='Elige un talle para tu stock')
    posesion = forms.ModelChoiceField(queryset=User.objects.all(), help_text='Elige quien tiene tu stock')
    stock = forms.IntegerField(max_value=50, min_value=1, help_text='Elige cuanto stock tienes')



class RopaTransferForm(forms.Form):
    user = forms.ModelChoiceField(queryset=User.objects.all(), help_text='Elige a que usuario deseas transferir la ropa')
    stock = forms.IntegerField(max_value=50, min_value=1)


class RopaReturnForm(forms.Form):
    user = forms.ModelChoiceField(queryset=User.objects.filter(groups__name='administrador'), help_text='Elige al administrador que le devuelves la ropa')
    stock = forms.IntegerField(max_value=50, min_value=1, help_text='Elige a quien le devuelves la ropa')
    ROPA_ESTADO = (
        ('v', 'Vendida'),
        ('d', 'Devuelta'),
    )
    estado = forms.ChoiceField(choices=ROPA_ESTADO, initial='v', help_text='Elige si marcas el stock como vendido o como devuelto')

mainApp/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect
from .models import Ropa, RopaInstance
from .forms import RopaModelForm, RopaEditForm, RopaInstanceCreateForm, RopaTransferForm, RopaReturnForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.models import User


class IndexView(generic.TemplateView):
    def get(self, request, **kwargs):
        ropa_list = Ropa.objects.order_by('cod')
        context = {'ropa_list': ropa_list}
        return render(request, 'mainApp/index.html', context)


class AboutView(generic.TemplateView):
    template_name = "mainApp/about.html"


class RopaDetailView(generic.DetailView):
    model = Ropa

    def get_context_data(self, **kwargs):
        context = super(RopaDetailView, self).get_context_data(**kwargs)
        query = RopaInstance.objects.filter(ropa=self.kwargs['pk']).order_by('id')
        lista = []
        tupledup = []
        for ropa in query:
            ropatup = (ropa.color, ropa.talle, ropa.estado, ropa.posesion)
            if ropatup not in tupledup:
                lista.append(ropa)
                tupledup.append(ropatup)
        context['lista'] = lista
        return context


class RopaEditView(UpdateView):
    model = Ropa
    fields = ['name', 'precio', 'categoria', 'desc', 'image']


class RopaDeleteView(DeleteView):
    model = Ropa
    success_url = reverse_lazy('index')


class RopaInstanceCreateView(CreateView):
    model = RopaInstance
    fields = ['posesion', 'talle', 'color']

    def form_valid(self, form):
        form.instance.ropa = Ropa.objects.get(pk=self.kwargs['pk'])
        return super(RopaInstanceCreateView, self).form_valid(form)


class RopaInstanceDetailView(generic.DetailView):
    model = RopaInstance


class RopaInstanceDeleteView(DeleteView):
    model = RopaInstance
    success_url = reverse_lazy('index')


def create_ropa(request):
    form = RopaModelForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/')
    else:
        return render(request, 'mainApp/create.html', {'form': form})


def create_ropainstance(request, pk):
    form = RopaInstanceCreateForm(request.POST or None)
    instance_bulk = []
    if request.method == 'POST':
        if form.is_valid():
            for i in range(0, form.cleaned_data['stock']):
                instance = RopaInstance()
                instance.ropa = Ropa.objects.get(cod=pk)
                instance.color = form.cleaned_data['color']
                instance.talle = form.cleaned_data['talle']
                instance.posesion = form.cleaned_data['posesion']
                instance_bulk.append(instance)
            RopaInstance.objects.bulk_create(instance_bulk)
        return HttpResponseRedirect('/')
    else:
        return render(request, 'mainApp/ropainstance_form.html', {'form': form})


def edit_ropa(request, pk):
    form = RopaEditForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        form.cod = pk
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/')
    else:
        return render(request, 'mainApp/ropa_edit.html', {'form': form})


def search(request):
    ropa_list = Ropa.objects.all()
    ropa_filter = RopaFilter(request.GET, queryset=ropa_list)
    return render(request, 'mainApp/ropa_search.html', {'filter': ropa_filter})


def transfer_stock(request, pk):
    form = RopaTransferForm(request.POST or None)
    instance = RopaInstance.objects.get(pk=pk)
    if request.method == 'POST':
        if form.is_valid():
            query = RopaInstance.objects.all()
            lista = []
            for ropa in query:
                if ropa.color == instance.color and ropa.talle == instance.talle and ropa.estado == instance.estado and ropa.ropa == instance.ropa:
                    lista.append(ropa.id)
            if form.cleaned_data['stock'] > instance.get_copies_count():
                return HttpResponseRedirect('/')
            else:
                modify = lista[:form.cleaned_data['stock']]
                RopaInstance.objects.filter(id__in=modify).update(estado='e', posesion=form.cleaned_data['user'])
                return HttpResponseRedirect('/')
    else:
        return render(request, 'mainApp/ropa_transfer.html', {'form': form, 'ropa': instance})


def return_ropa(request, pk):
    form = RopaReturnForm(request.POST or None)
    instance = RopaInstance.objects.get(id=pk)
    if request.method == 'POST':
        if form.is_valid():
            query = RopaInstance.objects.all()
            lista = []
            instancetuple = (instance.color, instance.talle, instance.estado, instance.posesion)
            for ropa in query:
                ropatuple = (ropa.color, ropa.talle, ropa.estado, ropa.posesion)
                if ropatuple == instancetuple:
                    lista.append(ropa.id)
            if form.cleaned_data['stock'] > instance.get_copies_count():
                return HttpResponseRedirect('/')
            else:
                modify = lista[:form.cleaned_data['stock']]
                RopaInstance.objects.filter(id__in=modify).update(estado=form.cleaned_data['estado'], posesion=form.cleaned_data['user'])
                return HttpResponseRedirect('/')
    return render(request, 'mainApp/ropa_return.html', {'form': form, 'ropa': instance})

mainApp/templates/mainApp/about.html
{% extends "base_generic.html" %}
{% block content %}
        <h1>Todo lo que tenes que saber de JandraClothes</h1>
    <p>
      En JandraClothes podras subir articulos, controlar su stock y buscar por su clave o nombre
    </p>
    <a href="/">Go back home</a>
{% endblock %}

mainApp/templates/mainApp/create.html
{% extends "base_generic.html" %}
{% block content %}
        <h1>Es hora de crear tu ropa</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
            <input type="submit" value="Submit">
        </form>
    <a href="/">Go back home</a>
{% endblock %}

mainApp/templates/mainApp/index.html
<!-- mainApp/templates/index.html -->
{% extends "base_generic.html" %}
{% block content %}

        <h1>CATALOGO DE ROPA</h1>

        {% if ropa_list %}
        <table class="table table-bordered">

          <tr>
            <th>Codigo de Producto</th>
            <th>Nombre Producto</th>
            <th>Descripcion</th>
            <th>Stock</th>
            <th>img</th>
          </tr>
          </thead>
          {% for ropa in ropa_list %}
          <tr>
            <td>{{ ropa.cod }}</td>
            <td><a href="{{ ropa.get_absolute_url }}"> {{ ropa.name }} </a></td>
            <td>{{ ropa.desc }}</td>
            <td>{{ ropa.ropainstance_set.all.count }}</td>
            {% if ropa.image %}
            <td><img src="{{ropa.image.url}}" width="240"></td>
            {% else %}
            <td>SIN IMAGEN</td>
            {% endif %}
            <td><p><a href="{{ropa.get_edit_url}}"> Edita tu ropa </a></p>
              <p><a href = '{% url 'ropa-delete' ropa.cod %}'>Borra tu Ropa</a></p></td>
          </tr>
          {% endfor %}
        </table>

        {% else %}
          <p>No hay ninguna ropa en la base de datos</p>
        {% endif %}

        <a href="{% url 'about' %}">Sobre la App</a>
{% endblock %}

mainApp/templates/mainApp/ropa_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
{% if perms.catalog.can_mark_returned %}

<h1>Borrar Ropa</h1>

<p>Estas seguro que quieres borrar este tipo de ropa?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Si, borrar." />
</form>
{% else %}
<h1>YOU HAVE NO PERMISSION TO DO THAT</h1>
<strong><a href="{% url 'index' %}">BABY GO BACK!</a></strong>
{% endif %}

{% endblock %}

mainApp/templates/mainApp/ropa_detail.html
{% extends "base_generic.html" %}
{% block content %}
<h1>{{ ropa.name }}</h1>

<p><strong>Codigo: </strong>{{ ropa.cod }}</p> <!-- author detail link not yet defined -->
<p><strong>Descripcion: </strong> {{ ropa.desc }}</p>
<p><strong>Precio: </strong> {{ ropa.precio }}</p>
<p><strong>Categoria: </strong> {{ ropa.categoria }}</p>
{% if ropa.image %}
<td><img src="{{ropa.image.url}}" width="240"></td>
{% endif %}
<a href = "{% url 'ropainstance-create' pk=ropa.cod %}">Insertar un stock de esta ropa</a>
<hr>
<p><strong>Stock del producto</strong></p>
{% for copy in lista %}
<hr>
<p class="{% if copy.estado == 'e' %}text-success{% elif copy.estado == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_estado_display }}</p>
<p><strong>En posesion de:</strong> {{copy.posesion}}</p>
<p>Talle : {{copy.talle}}</p>
<p>Color: {{copy.color}}</p>
<p>Copias: {{copy.get_copies_count}}</p>

<p class="text-muted"><a href="{% url 'ropainstance-detail' copy.id %}"><strong>Id:</strong> {{copy.id}}</a></p>
{% endfor %}
</div>
{% endblock %}

mainApp/templates/mainApp/ropa_form.html
{% extends "base_generic.html" %}
{% block content %}
    <body>
        <h1>Es hora de editar tu ropa</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
            <input type="submit" value="Submit">
        </form>
    <a href="/">Go back home</a>
    {% endblock %}

mainApp/templates/mainApp/ropa_return.html
{% extends "base_generic.html" %}
{% block content %}
    <body>
        <h1>Es hora de devolver tu ropa</h1>
        <h2><strong>STOCK DISPONIBLE: </strong>{{ropa.get_copies_count}}</h2>
        <form action="" method="post">
            {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
            <input type="submit" value="Submit">
        </form>
    <a href="/">Go back home</a>
    {% endblock %}

mainApp/templates/mainApp/ropa_search.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Buscando Ropa</h1>
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit" class="btn btn-primary">
      <span class="glyphicon glyphicon-search"></span> Search
    </button>
  </form>
  <p></p>
  <thead>
    <table class="table table-bordered">
    <tr>
      <th>Codigo de Producto</th>
      <th>Nombre Producto</th>
      <th>Descripcion</th>
      <th>Stock</th>
      <th>img</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for ropa in filter.qs %}
    <tr>
      <td>{{ ropa.cod }}</td>
      <td><a href="{{ ropa.get_absolute_url }}"> {{ ropa.name }} </a></td>
      <td>{{ ropa.desc }}</td>
      <td>{{ ropa.ropainstance_set.all.count }}</td>
      {% if ropa.image %}
      <td><img src="{{ropa.image.url}}" width="240"></td>
      {% else %}
      <td>SIN IMAGEN</td>
      {% endif %}
      <td>{{ ropa.ropainstance_set.all.count }}</td>
      <td><p><a href="{{ropa.get_edit_url}}"> Edita tu ropa </a></p>
          <p><a href = '{% url 'ropa-delete' ropa.cod %}'>Borra tu Ropa</a></p></td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
<a href="/">Go back home</a>
{% endblock %}

mainApp/templates/mainApp/ropa_transfer.html
{% extends "base_generic.html" %}
{% block content %}
    <body>
        <h1>Es hora de transferir tu ropa</h1>
        <h2><strong>STOCK DISPONIBLE: </strong>{{ropa.get_copies_count}}</h2>
        <form action="" method="post">
            {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
            <input type="submit" value="Submit">
        </form>
    <a href="/">Go back home</a>
    {% endblock %}

mainApp/templates/mainApp/ropainstance_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
{% if perms.catalog.can_mark_returned %}

<h1>Borrar Prenda</h1>

<p>Estas seguro que quieres borrar la prenda?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Si, borrar." />
</form>
{% else %}
<h1>YOU HAVE NO PERMISSION TO DO THAT</h1>
<strong><a href="{% url 'index' %}">BABY GO BACK!</a></strong>
{% endif %}

{% endblock %}

mainApp/templates/mainApp/ropainstance_detail.html
{% extends "base_generic.html" %}
{% block content %}
<h1><a href="{% url 'ropa-detail' ropainstance.ropa.cod %}">Ropa de tipo {{ ropainstance.ropa.name }}</a></h1>
<p><strong>Codigo: </strong> {{ ropainstance.ropa.cod }}</p>
<p><strong>Categoria: </strong> {{ropainstance.ropa.categoria }}</p>
<p><strong>Precio:</strong> {{ ropainstance.ropa.precio }}</p>
{% if ropainstance.ropa.image %}
<td><img src="{{ropainstance.ropa.image.url}}" width="240"></td>
{% endif %}
<p>{{ ropainstance.get_estado_display }}<p>
<p><strong>En posesion de:</strong> {{ropainstance.posesion}}</p>
<p>Talle : {{ropainstance.talle}}</p>
<p>Color : {{ropainstance.color}}</p>

<p class="text-muted"><strong>Id:</strong> {{ropainstance.id}}</p>

<p><a href = '{% url 'ropainstance-delete' ropainstance.id %}'>Borra tu Prenda</a></p>

<p><a href = '{% url 'transfer-stock' ropainstance.id %}'>Transferi prendas</a></p>


<p><a href = '{% url 'mark-returned' ropainstance.id %}'>Marca como vendida o retorna tu prenda!</a></p>

</div>
{% endblock %}

mainApp/templates/mainApp/ropainstance_form.html
{% extends "base_generic.html" %}
{% block content %}
    <body>
        <h1>Es hora de insertar stock</h1>
        <form action="" method="post">
            {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
            <input type="submit" value="Submit">
        </form>
    <a href="/">Go back home</a>
{% endblock %}